version: '2'
services:
  editor_dev:
    extends:
      file: docker/common.yml
      service: editor
    entrypoint: /var/editor/docker/entrypoint.sh dev
  editor_prod:
    extends:
      file: docker/common.yml
      service: editor
    entrypoint: /var/editor/docker/entrypoint.sh dist
